### ISSUE TITLE
Assumption "project.version is String" leads to incompatibilities with other plugins

### ISSUE THREAD

**Issue by AlinaDev** [IBM/cics-bundle-gradle#111]
Because it is assumed, that the project.version ist always a String, this plugin is incompatible with semantic release-plugins (e.g. https://github.com/tschulte/gradle-semantic-release-plugin):
https://github.com/IBM/cics-bundle-gradle/blob/a27c3c84571fc9905fc9e067d143ddbb1ef9cdee/src/main/kotlin/com/ibm/cics/cbgp/BuildBundleTask.kt#L113

In the gradle documentation it is stated, that project.version should always be used with toString():
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:version

In the gradle javadoc, getVersion() also returns an Object. It can not be assumed, that the version is always a String:
https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getVersion

**Comment by stewartfrancis** [comment]
Thanks for the bug report and the diagnosis.  I'll work on putting together a fix

**Comment by tom-foyle** [comment]
Hi @AlinaDev. I've delivered a fix to address this. It is available in the latest development SNAPSHOT build if you want to try it out. Thanks again.

**Comment by ind1go** [comment]
This fix is now live in [release 1.0.3](https://github.com/IBM/cics-bundle-gradle/releases/tag/1.0.3).
