### ISSUE TITLE
project.version sometimes evaluates to "unspecified" when plugin is applied

### ISSUE THREAD

**Issue by tom-foyle** [IBM/cics-bundle-gradle#16]
The buildCICSBundle task uses the value of project.version in it's output folder:
```
this.outputDirectory.set(project.layout.buildDirectory.dir("${project.name}-${project.version}"))
```
If the plugin is applied before the version number is set then it will come out as "unspecified" in the output folder. It's not clear to me what order things happen in. In the integration test for a standalone bundle/war project with the below config, I get "unspecified", but when running the same scenario manually the version number is resolved correctly to '1.0.0'.
```
plugins {
    id 'war'
    id 'com.ibm.cics.bundle' version '0.0.1-SNAPSHOT'
}
version '1.0.0'
```
Can be fixed by delaying the setting of the outputDirectory until after the project is evaluated, like so:
```
project.afterEvaluate() {
    buildTaskProvider.get().outputDirectory.set(project.layout.buildDirectory.dir("${project.name}-${project.version}"))
}

**Comment by ind1go** [comment]
I think the preference would be to do similar to the suggested workaround but in the plugin using the `projectsEvaluated` hook as per [this question](https://stackoverflow.com/questions/13198358/how-to-get-project-version-in-custom-gradle-plugin).

**Comment by tom-foyle** [comment]
I'm seeing the same issue with values like defaultJVMServer as I was with project.version, so I've put everything in projectsEvaluated to ensure all values are set.
