### ISSUE TITLE
Deploying bundle with a JAR/OSGi bundle part fails

### ISSUE THREAD

**Issue by tom-foyle** [IBM/cics-bundle-gradle#17]
I've not yet been able to successfully deploy a bundle with a JAR type cicsBundle dependency, such as:
```
dependencies {
    cicsBundle(group: 'org.codehaus.cargo', name: 'simple-bundle', version: '1.7.7', ext: 'jar')
}
```
DFHSJ1004 04/02/2020 13:22:12 IYCWEMW2 CICSUSER An exception has been thrown by the route method of class com/ibm/cics/router/Router running in JVMSERVER EYUCMCIJ.
Exception 'Bundlepath: /u/expauto/bundles/gradle-demo-multi-bundle_1.0.0/ Symbolic-name: simple-bundle-1.7.7 Version: 1.7.7 could not be found.'.

**Comment by ind1go** [comment]
Looks like the version is being injected into the symbolic name - need to ensure we're using the `symbolicName` from the [`com.ibm.cics.bundle.parts.OsgiBundlePart`](https://github.com/IBM/cics-bundle-common/blob/master/src/main/java/com/ibm/cics/bundle/parts/OsgiBundlePart.java), not just the `name`.
