### ISSUE TITLE
Gradle offline build

### ISSUE THREAD

**Issue by marcredhat** [IBM/cics-bundle-gradle#69]
Hi,

I'm testing using https://www.ibm.com/it-infrastructure/z/resources/trial.
As there is no Internet access from the CICS lab, is it possible to do a Gradle offline build?
I can copy the Gradle cache from another machine but this does not include the com.ibm.cics.bundle plugin etc

Thanks,
Marc

**Comment by stewartfrancis** [comment]
Hiya.  I did a little experimentation around this.  The plugin's also published to Maven central, so the best I could come up with was mirroring the plugin's transitive dependency graph into a local Maven repo.  You could then copy that to your isolated machine, and tell gradle to resolve the plugin from there.  Here's the config I used to do that:

Mirror plugin and dependencies to `repo`:

```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get \
    -Dartifact=com.ibm.cics.bundle:com.ibm.cics.bundle.gradle.plugin:0.0.2:pom \
    -Dmaven.repo.local=repo -U
```

settings.gradle config to use `repo` as a source of plugins:

```
pluginManagement {
    repositories {
        maven {
            url 'repo'
        }
    }
}
```

You can then reference the plugin as normal in your build.gradle.  Note that you'll have to specify the version:

```
plugins {
    id 'com.ibm.cics.bundle' version '0.0.2'
}
```

Hopefully something like this works for you

**Comment by marcredhat** [comment]
Thanks a lot Stuart, worked liked a charm!
I still have an error when deploying the CICS bundle:
> Task :gradle-bundle-demo:buildCICSBundle UP-TO-DATE
> Task :gradle-bundle-demo:packageCICSBundle UP-TO-DATE

> Task :gradle-bundle-demo:deployCICSBundle FAILED
Task deployCICSBundle

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-bundle-demo:deployCICSBundle'.
> com.ibm.cics.bundle.deploy.BundleDeployException: <!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"><html><head><title>404 CICS Web Support Error</title></head><body><h1>404 CICS URL not found</h1><p>An error has occurred in CICS Web Support.CICS cannot locate a resource corresponding to the URL you have specified.</p><p><strong>Probable cause:</strong>Either no URIMAP definition is installed which matches the URL<tt>&lt;http://zos.dev:1490/managedcicsbundles&gt;</tt>,<br />or an incorrect analyzer program is specified in the TCPIPSERVICE definition.</p></body></html>

**Comment by ind1go** [comment]
Ah, the direct deployment to CICS is currently only available in the CICS TS 5.6 open beta - so the CICS region you're deploying to doesn't have it.

However, I think we could do a little more handling in the Gradle plugin to deal with 404s and mention that as a possible cause.

Out of interest, which Z Trial were you using - the CICS one?

**Comment by marcredhat** [comment]
Thanks Ben, I'm using the "IBM z/OS® Connect Enterprise Edition" Z Trial.
This is part of an experiment using Tekton pipelines
(similar to https://developer.ibm.com/technologies/devops/blogs/create-a-serverless-pipeline-using-newly-enhanced-tekton-features/)
to enable CI/CD
for OpenShift frontends
that interface with CICS backends,
making it easier to automate end-to-end dev/test/QA etc across multiple OpenShift and Z environments.

We have a Trello board to discuss this, I'd be happy to add you if you are interested.

**Comment by ind1go** [comment]
Thanks Marc - a good use case.

I will also pursue selective internet access to Maven Central or GPP from the Z Trial machines.

**Comment by marcredhat** [comment]
I now have my own 
IBM Z Development and Test Environment Enterprise Edition v12.0.5.0
I can help testing/documenting the CICS Gradle automation; I'd need help configuring CICS on ZD&T.
Please let me know if interested in working together on this.

**Comment by ind1go** [comment]
Hi Marc, that ZD&T should be more flexible for your purposes. I'll contact you to find out more.

**Comment by ind1go** [comment]
Closing this, as it's unrelated directly to the plugin.
