### ISSUE TITLE
Java resources being included in CICS bundle main directory

### ISSUE THREAD

**Issue by timhandler** [IBM/cics-bundle-gradle#70]
Hi,

I noticed when building a Spring Boot application artifacts within the Java project (src/main/resources directory) are being included within the newly built CICS bundle directory.

I have attached the output from the build using the --info option.  In there you can see the file application.properties being added to the CICS bundle in error.

> Task :buildCICSBundle
Excluding []
Caching disabled for task ':buildCICSBundle' because:
  Build cache is disabled
Task ':buildCICSBundle' is not up-to-date because:
  Output property 'outputDirectory' file C:\Tim\Projects\web-app\build\web-app-0.0.1-SNAPSHOT has been removed.
  Output property 'outputDirectory' file C:\Tim\Projects\web-app\build\web-app-0.0.1-SNAPSHOT\META-INF has been removed.
  Output property 'outputDirectory' file C:\Tim\Projects\web-app\build\web-app-0.0.1-SNAPSHOT\META-INF\cics.xml has been removed.
Task buildCICSBundle (Gradle 6.0.1)
Adding bundle parts to the bundle
Adding Java-based bundle parts from 'cicsBundle' dependency configuration
Adding Java-based bundle part: 'C:\Tim\Projects\web-app\build\libs\web-app-0.0.1-SNAPSHOT.war'
Adding non-Java-based bundle parts from 'src/main/resources'
Adding non-Java-based bundle part: 'application.properties'
:buildCICSBundle (Thread[Execution worker for ':',5,main]) completed. Took 0.293 secs.
:packageCICSBundle (Thread[Execution worker for ':',5,main]) started.

Thanks,
Tim Handler

**Comment by stewartfrancis** [comment]
Hi Tim.  The intent of including the contents of the `src/main/resources` folder is to allow you to add other bundle parts to your bundle by manually putting them in there.  Obviously this doesn't play nice with other plugins which are using `src/main/resources` for their own purposes. I think it'd make sense to change this to `src/main/bundleparts` and have it user-configurable, before we do a v 1.0.0 release, which would avoid issues like this.  @tom-foyle @ind1go what do you guys think?

**Comment by markcocker** [comment]
> `src/main/bundleparts`
I wondered if the name should include CICS as _bundle_ is a very overloaded term. eg. `cicsresources` or `cicsbundleparts`. It would be nice to copy/include non CICS bundle parts in the future.

**Comment by tom-foyle** [comment]
> 
> 
> Hi Tim. The intent of including the contents of the `src/main/resources` folder is to allow you to add other bundle parts to your bundle by manually putting them in there. Obviously this doesn't play nice with other plugins which are using `src/main/resources` for their own purposes. I think it'd make sense to change this to `src/main/bundleparts` and have it user-configurable, before we do a v 1.0.0 release, which would avoid issues like this. @tom-foyle @ind1go what do you guys think?

Yes I agree. And we should ideally update the Maven plugin to match.

I don't mind too much on the name. `cicsbundleparts` would match the terminology used in build.gradle. But it's a bit long, and not ideal if there is a chance of including non-CICS bundle parts in the future.

**Comment by ind1go** [comment]
This fix is now available in [release 1.0.1](https://github.com/IBM/cics-bundle-gradle/releases/tag/1.0.1).
